use_directory_urls: false
site_name: Fungus Docs
site_url: http://docs.fungusgames.com
site_description: Documentation and user guide for Fungus Unity dialog system
site_favicon: images/favicon.ico
pages:
- Home: index.md
- Recipes:
    - Quickstart: recipes/index.md
    - Next steps: recipes2/index.md
    - Audio: audio/index.md
- Fundamentals:
    - Flowcharts: flowcharts/index.md
    - Blocks: blocks/index.md
- Glossary: glossary/glossary.md

- Command Reference:
    - Animation Commands: commands/animation_commands.md
    - Audio Commands: commands/audio_commands.md
    - Camera Commands: commands/camera_commands.md
    - Flow Commands: commands/flow_commands.md
    - iTween Commands: commands/itween_commands.md
    - Narrative Commands: commands/narrative_commands.md
    - Scripting Commands: commands/scripting_commands.md
    - Sprite Commands: commands/sprite_commands.md
    - Variable Commands: commands/variable_commands.md
    - Events (Core) Commands: commands/event_handlers/core_events.md
    - Events (Input) Commands: commands/event_handlers/input_events.md
    - Events (Sprite) Commands: commands/event_handlers/sprite_events.md
- Advanced Reference:
    - Narrative Parser Tokens: advanced/narrative_parser_tokens.md

theme: readthedocs


