site_name: Fungus Docs
site_url: http://docs.fungusgames.com
site_description: Documentation and user guide for Fungus Unity dialog system
pages:
- Home: index.md
- Recipes - quickstart: recipes/index.md
- Recipes - next steps: recipes2/index.md
- Fundamentals - Flowcharts & Blocks: flowcharts/index.md
- Recipes - audio: audio/index.md
- Advanced - Flowcharts & Blocks: advanced_flowcharts/index.md

theme: readthedocs
